const IN_PROVINCE_COST_MIN_60_KM = 200_000;
const OUT_PROVINCE_COST_SAME_ISLAND_MIN_60_KM = 250_000;
const OUT_PROVINCE_COST_DIFFERENT_ISLAND_MIN_60_KM = 300_000;
const ABOARD_COST_PERDAY = 50;

export {
  IN_PROVINCE_COST_MIN_60_KM,
  OUT_PROVINCE_COST_SAME_ISLAND_MIN_60_KM,
  OUT_PROVINCE_COST_DIFFERENT_ISLAND_MIN_60_KM,
  ABOARD_COST_PERDAY,
};
